// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzxapnexanyeqpmjqhoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6eGFwbmV4YW55ZXFwbWpxaG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTE1OTAsImV4cCI6MjA1NTcyNzU5MH0.-G72O71C6KxX-dc3WyDY4B0cbYQkTX6WlkiAxbWcFGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);